version: '2'
services:
  app:
    container_name: scheduler-backend-nodejs
    build: .
    restart: always
  web:
    build: .
    ports: 
      - 8080:8080
  db:
    image: mongodb
    environment:
      - MONGO_DB_PASSWORD: password 
    volumes:
      - db-data:/scheduler
